version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - mongodata:/data/db
    #environment:
    #MONGO_INITDB_ROOT_USERNAME:memo
    #MONGO_INITDB_ROOT_PASSWORD:verysecretpassword
    #- MONGO_INITDB_ROOT_USERNAME=memo
    #- MONGO_INITDB_ROOT_PASSWORD=verysecretpassword
    env_file:
      - ./.env

  backend:
    #build: ./backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 82:80
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

#named volumes have to be listed in that way also
volumes:
  mongodata:
  logs:
